### ISSUE TITLE
"Insert image" in the RTE

### ISSUE THREAD

**Issue by tobloyd** [llcit/clt-langlabs-dev-py#11]
"Insert image" in the RTE:

the option to insert an image is limited to external links (no upload option). The box says "source" rather than "URL" or "Image Address". "Source" doesn't make it clear that it's only possible to insert images hosted somewhere online rather than the source being a local computer folder.

**Comment by tobloyd** [comment]
Commenting on post in an essay activity:

it is unclear how to submit a comment. Pressing enter to insert a line break navigates away from the page. (presumably "enter" has submitted the comment, bit the user has no way of knowing that).

Without the ability to edit or delete comments, we cannot have "enter" submit them. People will constantly embarrass themselves by trying to insert line breaks and submitting incomplete comments

**Comment by richmedina** [comment]
richard will consider removing _insert image_ from tiny mce toolbar.
